### ISSUE TITLE
Implement addVersion

### ISSUE THREAD

**Issue by adamhammes** [adamhammes/cs362#48]

**Comment by adamhammes** [comment]
putUser needs to add versions as well

**Comment by njriesen** [comment]
Are we separating put user and put book into there own operations? I can add it to put user, but I think that should belong to putBook, because system has direct access to books.

**Comment by adamhammes** [comment]
I think putBook has to exist to add ratings. Since ratings exist for all
users, there needs to be an independent putBook for that. At least that's
my thinking.

**Comment by njriesen** [comment]
Do books not exist for all users? I was under the impression that different owners could own the same instance of book. Isn't that the point of the joining table _book_account_?

**Comment by adamhammes** [comment]
I think that the putBook method will only be used for changes that apply to
the book across the system, like ratings and authors.

Whereas tags and versions are specific to a user, so (to me) they should go
through User.

I by no means am certain on any of this though.

**Comment by njriesen** [comment]
Do you have a domain model? The one on the site has no arrows. I think we are each thinking of slight variations on the domain model.
